[package]
name = "asyn_crpto"
version = "0.1.0"
edition = "2021"
features=["pem"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.8.5"
rsa = {version="0.7.2"}

chrono = "0.4.23"
base64 = "0.20.0"